// Code generated by go generate; DO NOT EDIT.
//
// file generated at: 2019-11-11 15:33:50.244913 -0700 MST m=+0.721735917
// using data from:   https://raw.github.com/afiune/godist/master/glob_dist.json
// and generator:     https://github.com/afiune/godist
//

package main

var (
	AutomateProduct = "Chef Automate"
	ClientExec      = "chef-client"
	ClientProduct   = "Chef Infra Client"
	MainWebsite     = "https://chef.io"
	ServerProduct   = "Chef Infra Server"
	ShellExec       = "chef-shell"
	SoloExec        = "chef-solo"
	SoloProduct     = "Chef Infra Solo"
	ZeroExec        = "chef-zero"
)
